# Generated by Django 5.1.3 on 2024-11-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('app_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='home_news_slug_2cb4a1_idx'), models.Index(fields=['created_at'], name='home_news_created_d7a3dc_idx')],
            },
        ),
    ]
