# Generated by Django 5.1.1 on 2024-09-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_laptops_description_laptops_model_laptops_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
