# Generated by Django 5.1.1 on 2024-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_alter_laptops_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='name',
        ),
        migrations.AddField(
            model_name='laptops',
            name='publishd_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laptops',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
